spring:
  data:
    mongodb:
      uri: mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}/?retryWrites=true&w=majority
      database: ${env.MONGO_DATABASE}
  application:
    security:
      jwt:
        secret-key: 8adeb58a034b296f1984ce77d8339e249d0e1b055c5835e832c73c8ca6c874eb
        expiration: 86400000
        refresh-token:
          expiration: 604800000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 72227945083-6ioli3a14g9535h8qjihc7vlr0q143qm.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          github:
            client-secret: d6d1437a36f0a01aa8e36a36d61bec697cd1f4b0
            client-id: ed59386a1e2696c26afc
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - public_profile
              - user:email
  mail:
    host: smtp.gmail.com
    port: 587
    username: mishamakytonin@gmail.com
    password: auiofemthablznyw
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
logging:
  level:
    org.springframework.security: trace
